---
title: "2-network"
author: "Bernard"
date: "2021-09-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Packages

```{r message=FALSE, warning=FALSE}
# Tidying
library (tidyverse)
library (skimr)
library (arsenal)

# Network analysis
library (qgraph)
library (bootnet)
library (mgm)
library (huge)

# Office
library (officer)
library (flextable)

# Plot 
library (cowplot)
library (plotrix)

# Parallel
library(foreach)
library(doParallel)

# HTML table
library (kableExtra)

```

# Load data

```{r}
df <- readRDS("output/df_clean.RDS")

```

```{r}
skim (df)
```


# Select variables

```{r}
vars_keep <- c("age",
               "gender",
               "marital_status",
               "education",
               "comorbidities",
               "number_pain_sites",
               "pain_intensity",
               "chronicity",
               "frequency",
               "evolution",
               "interference",
               "change_in_tx",
               "pcs",
               "tsk",
               "job",
               "sad",
               "worry",
               "lonely",
               "anger",
               "helpless",
               "anxiety",
               "surprise",
               "relief",
               "hope",
               "stress_covid",
               "gad",
               "ious",
               "se")

names2use <- c("Age",
               "Gender",
               "Marital_status",
               "Education",
               "comorbidities",
               "Number_pain_sites",
               "Pain_intensity",
               "Chronicity",
               "Frequency",
               "Pain_evolution",
               "Interference",
               "Change_in_tx",
               "Pcs",
               "Tsk",
               "Job",
               "Sad",
               "Worry",
               "Lonely",
               "Anger",
               "Helpless",
               "Anxiety",
               "Surprise",
               "Relief",
               "Hope",
               "Stress_covid",
               "Gad",
               "Ious",
               "Se")

df_sub <- df %>%
  dplyr::select (all_of (vars_keep)) %>%
  mutate_if(is.character, tolower) %>%
  mutate (gender = ifelse (gender == "h", "0", "1"), # 0 = male, 1= female
          comorbidities = ifelse (comorbidities == "no", "0", "1"),
          chronicity = ifelse (chronicity == "acute", "0", "1"),
          frequency = ifelse (frequency == "constantly", "0", 
           ifelse (frequency == "daily", "1",
                   ifelse (frequency == "weekly", "2", "3"))),
          change_in_tx = ifelse (change_in_tx== "no", "0", "1"))

```

```{r}

meanNsd_transform <- function (x) {

  m <- round (x[[1]][1], 2)
  s <- round (x[[1]][2], 2)

  m_s <- paste0(m, "(", s, ")")

  return (m_s)
}

demo <- df_sub %>%
  select (where (is.numeric), everything())

tab1 <- tableby ( ~. , data = demo, digits = 2, digits.p = 2) %>%
  as.data.frame() %>%
  filter (!term %in% c("Nmiss", "range")) %>%
  select (-c(group.term:term, variable.type, Total)) 


tab2 <-  tab1[-c (seq (1, 37, 2), 39, 42, 45, 48, 51, 54, 59, 62, 65),]
tab2$label <- c("Age", "Pain sites", "Pain intensity", "Pain interference","PCS", 
                "TSK", "Sad", "Worry", "Lonely", "Anger", "Helpless", "Anxiety",
                "Surprise", "Relief", "Hope", "Stress of Covid", "GAD", "IOUS", "SE", 
                "Sex - Male", "Sex - Female", 
                "Marital status - Married", "Marital status - Others",
                "Education - University", "Education - Others",
                "Comorbidities - No", "Comorbidities - Yes",
                "Chronicity - Acute", "Chronicity - Chronic",
                "Frequency - Constant", "Frequency - Daily", 
                "Frequency - Weekly", "Frequency - Occasionally",
                "Pain Evolution - Worse", "Evolution - Others",
                "Change in treatment - No", "Change in treatment - Yes",
                "Job - Full-time", "Job - Others")

for(row in 1:nrow(tab2)) {
    tab2[row, 2] <- meanNsd_transform (tab2[row, 2])
  }

tab2 <- unnest(tab2, Overall)

colnames (tab2) <- c ("Variables", 
                      "Summary value")



my_path <- paste0("manuscript/SM_table1", 
                  "baseline",
                  ".docx")

ft <- flextable(tab2) %>%
  set_caption(caption = " Table 1.Baseline descriptive characteristics of cohort") %>%
  autofit() 

my_doc <- read_docx()  %>% 
  body_add_flextable(ft)

print (my_doc, target = my_path)
```


## Create subgroup datasets

```{r}
# Sex
df_sub_f <- df_sub %>%
  filter (gender == "1") %>%
  select (-gender)
df_sub_m <- df_sub %>%
  filter (gender == "0")%>%
  select (-gender)
nrow(df_sub_m) + nrow(df_sub_f) == nrow (df_sub)

# Chronicity
df_sub_c <- df_sub %>%
  filter (chronicity == "1")%>%
  select (-chronicity)
df_sub_a <- df_sub %>%
  filter (chronicity == "0")%>%
  select (-chronicity)
nrow(df_sub_a) + nrow(df_sub_c) == nrow (df_sub)

df_list <- list (df = df_sub,
                 fema = df_sub_f,
                 male = df_sub_m,
                 acute = df_sub_a,
                 chronic = df_sub_c)
```


# Network analysis

## Get column types

```{r}

stats_type <- c("strength", "betweenness", "expectedInfluence", "closeness")

my_huge <- function (df, col_type) {

  df[, col_type == "g"] <- huge::huge.npn (df[, col_type == "g"])

  return (df)

}

nlvls_list <- col_type_list <- var_names_list <- new_name_list <- vector ("list", length (df_list))

for (n in seq_along(df_list)) {
  
  nlvls_list[[n]] <- df_list[[n]] %>%
                      map_if(is.numeric, function (x) x =1 ) %>%
                      map_if(is.character, n_distinct) %>%
                      unlist ()
  
  col_type_list[[n]]  <- df_list[[n]] %>%
                          map_chr(class) 

  col_type_list[[n]]  <- ifelse (col_type_list[[n]] == "numeric", "g", "c")
  
  df_list[[n]] <- df_list[[n]] %>%
                  mutate_if (is.character, factor) %>%
                  mutate_if (is.factor, as.numeric) %>%
                  mutate_if (nlvls_list[[n]] == 2, ~.x-1)
  
  var_names_list[[n]] <- names(df_list[[n]])

}

new_names <- paste0("V", seq(1:ncol (df_list[[1]])))
names(new_names) <- names(df_list[[1]])

names(df_list[[1]]) <- new_names
names(df_list[[2]]) <- new_names[names(new_names) %in% names(df_list[[2]])]
names(df_list[[3]]) <- new_names[names(new_names) %in% names(df_list[[3]])]
names(df_list[[4]]) <- new_names[names(new_names) %in% names(df_list[[4]])]
names(df_list[[5]]) <- new_names[names(new_names) %in% names(df_list[[5]])]

```

## Analysis

```{r, eval = FALSE}
# Network analysis
set.seed(1)

nw_list <- centr_list <- centr_stb_list <- edgewts_list <- vector ("list", length (df_list))

df_list <- list (df = df_list, col_type = col_type_list) %>%
  pmap (my_huge) 

for (n in seq_along(df_list)) {
  
  nw_list[[n]] <- estimateNetwork (data = df_list[[n]],
                                default = "mgm",
                                 type= col_type_list[[n]],
                                 level= nlvls_list[[n]],
                                 criterion  = "CV",# we used cross validation to select optimal tuning parameter
                                 nFolds = 10, # using 10 folds
                                 order = 2,# we only include second order interactions
                                 binarySign = TRUE,
                                 scale = TRUE,
                                .pbar = FALSE,
                                .signInfo = FALSE)
}

# Centrality stability
B <-  1000

registerDoParallel(cores = 3)
centr_stb_list <- foreach (n = 1:length (df_list), .packages = "bootnet") %do% 
  bootnet (nw_list[[n]],
           nBoots = B,
           type = "case",
           statistics = stats_type)
stopImplicitCluster()

# Edgeweights stability

registerDoParallel(cores = 3)
  edgewts_list <- foreach (n = 1:length (df_list), .packages = "bootnet") %do% 
    bootnet (nw_list[[n]],
             nBoots = B)
stopImplicitCluster()


```

# Save results

```{r, eval = FALSE}
res <- list (data = df_list,
             names = var_names_list,
             nw = nw_list,
             stb = centr_stb_list,
             wts =  edgewts_list,
             original = df_sub)

saveRDS(res,
        "output/res.RDS")
```

# Import

```{r}
res <- readRDS("output/res.RDS")
list2env(res,globalenv())
rm(res)
```

```{r}

names <- names %>%
  map (~ ifelse (.x == "evolution", "pain_evolution", .x))
```

# Report

## Networks

```{r fig.height=30, fig.width=25, message=FALSE, warning=FALSE}

par (mfrow = c(3,2))

plot.new()
# addtable2plot(0,
#               -15,
#               data.frame (var = names (df_list[[1]]),
#                              names = var_names_list[[1]]),
#               xpad=0, 
#               ypad=0,
#               bty='o',
#               cex = 1,
#               display.rownames = FALSE,
#               hlines = TRUE,
#               vlines = TRUE)


plot (nw[[1]], title = "Cohort", label.cex = 3, vsize = 5, curve = 0.4, curveAll = TRUE, title.cex = 5)
p2 <- plot (nw[[2]], title = "Female", label.cex = 3, vsize = 5, curve = 0.4, curveAll = TRUE, title.cex = 5)
p3 <- plot (nw[[3]], title = "Male", layout = p2$layout, label.cex = 3, vsize = 5, curve = 0.4, curveAll = TRUE, title.cex = 5)
p4 <- plot (nw[[4]], title = "Acute",  label.cex = 3, vsize = 5, curve = 0.4, curveAll = TRUE, title.cex = 5)
p5 <- plot (nw[[5]], title = "Chronic", layout = p4$layout, label.cex = 3, vsize = 5, curve = 0.4, curveAll = TRUE, title.cex = 5)

```


```{r fig.height=30, fig.width=25, message=FALSE, warning=FALSE}

# Cohort
png ("manuscript/fig1.png", width = 15, height = 8, units = "in", res = 100)
  plot (nw[[1]], 
        title = "Cohort", 
        label.cex = 1.5, 
        vsize = 5, 
        curve = 0.4, 
        curveAll = TRUE, 
        legend =TRUE,
        nodeNames = names[[1]],
        title.cex = 2)
dev.off()

#Subgroup sex

png ("manuscript/fig2.png", width = 20, height = 8, units = "in", res = 100)
par (mfrow = c(1,3))

  p2 <- plot (nw[[2]], 
              title = "Female", 
              label.cex = 1.5, 
              vsize = 6, 
              curve = 0.4, 
              curveAll = TRUE, 
              title.cex = 2)
  p3 <- plot (nw[[3]], 
              title = "Male", 
              layout = p2$layout, 
              label.cex = 1.5, 
              vsize = 6, 
              curve = 0.4, 
              curveAll = TRUE, 
              title.cex = 2)
  plot.new()
  addtable2plot(0,
                0,
                data.frame (var = names (data[[2]]),
                           names = names[[2]]),
                xpad=0,
                ypad=1,
                bty='o',
                cex = 1.2,
                display.rownames = FALSE,
                hlines = TRUE,
                vlines = TRUE)

dev.off()

# Subgroup chronicity

png ("manuscript/fig3.png", width = 20, height = 8, units = "in", res = 100)
par (mfrow = c(1,3))

  p4 <- plot (nw[[4]], 
              title = "Acute", 
              label.cex = 1.5, 
              vsize = 6, 
              curve = 0.4, 
              curveAll = TRUE, 
              title.cex = 2)
  p5 <- plot (nw[[5]], 
              title = "Chronic", 
              layout = p4$layout, 
              label.cex = 1.5, 
              vsize = 6, 
              curve = 0.4, 
              curveAll = TRUE, 
              title.cex = 2)
  plot.new()
  addtable2plot(0,
                0,
                data.frame (var = names (data[[4]]),
                           names = names[[4]]),
                xpad=0,
                ypad=1,
                bty='o',
                cex = 1.2,
                display.rownames = FALSE,
                hlines = TRUE,
                vlines = TRUE)
dev.off()

```


```{r}

var_df <- data.frame (var = names (df_list[[1]]),
                      names = var_names_list[[1]])
var_df  %>%
  kbl(caption = "Variable names") %>%
  kable_styling() %>%
  scroll_box(width = "500px", height = "500px")
```

## Importance

```{r, fig.height=30, fig.width=20, message=FALSE, warning=FALSE}

png ("manuscript/fig4.png", width = 15, height = 6, units = "in", res = 100)

c_fig <- pmap (list (nw, labels = names), centralityPlot, include = c("Strength"),  
              print = FALSE, scale = "relative") %>%
  map (~.x + 
                  scale_x_continuous(breaks= c(0, 0.5, 1), lim = c(0, 1)) + 
                  theme_cowplot() + 
                  theme(strip.background = element_blank(), 
                        strip.text = element_blank()) + 
                  theme(text = element_text(size = 20), 
                        #axis.text.x = element_text(angle = 45, hjust = 1),
                        axis.text.y = element_text(angle = 30, hjust = 1)), 
              include = "all", print = FALSE, scale = "relative")

#tiff(width = 15, height = 15, units = "in", res = 100, file = "output/odi_strength.tiff")
cowplot::plot_grid(plotlist = c_fig, 
                   labels = c("a. Cohort","b. Female", "c. Male", "d. Acute", "e. Chronic" ), 
                   vjust = 1, 
                   hjust = -1, 
                   ncol = 5,
                   nrow = 1)
dev.off()
```



## Edgeweights stability

```{r, eval = FALSE, include = FALSE}
# Easy reporting in manuscript
n = 5

x <- summary (wts[[n]]) %>%
  ungroup () %>%
  filter (type == "edge" & sample != 0) %>%
  dplyr::select (id, node1, node2, sample, q2.5, q97.5) %>%
  mutate (samp_abs = abs (sample)) %>%
  #group_by(node1) %>%
  #slice_max (samp_abs, n = 4) %>%
  map_if (is.numeric, round, 2) %>%
  bind_cols()

x_max <- x %>%
  slice_max (samp_abs, n = 5)

```

```{r, fig.height=30, fig.width=20, message=FALSE, warning=FALSE}

png ("manuscript/fig5.png", width = 15, height = 6, units = "in", res = 100)

w_fig <- map (wts, plot, order = "sample", CIstyle = "quantiles", labels = FALSE, bootColor = "black",  areaAlpha = 0.6)

w_fig <- map (w_fig, 
              ~.x + 
                  theme_cowplot() + 
                  theme(strip.background = element_blank(), 
                        strip.text = element_blank(),
                        axis.text.y=element_blank()) +
                 guides(color = FALSE))

cowplot::plot_grid(plotlist = w_fig, 
                   labels = c("a. Cohort","b. Female", "c. Male", "d. Acute", "e. Chronic" ), 
                   vjust = 1, 
                   hjust = -1, 
                   ncol = 5,
                   nrow = 1)
dev.off()

```

## Centrality stability

```{r}
for (n in seq_along (df_list)) {
  
  c_val <- c_fig[[n]]$data %>%
    slice_max (value, n = 3) %>%
    pull (node) %>%
    unique () %>%
    as.character()
  
  cat ("At", names(df_list)[n], "across all three centrality measures, the three nodes with the greatest value was",     c_val[[1]], "and", c_val[[2]], c_val[[3]],"\n")
  
}
```


```{r fig.height=20, fig.width=20, message=FALSE, warning=FALSE}


png ("manuscript/fig6.png", width = 6, height = 10, units = "in", res = 100)
# Plot centrality stability
s_fig <- map (stb, plot, statistics = c( "strength"))

s_fig <- map (s_fig, ~.x + 
                theme_cowplot() + 
                ylab ("Ave Corr") + 
                  theme(text = element_text(size = 16), 
                        axis.text.x = element_text(angle = 90, hjust = 1),
                        legend.position = "none") + 
                geom_ribbon (alpha = 0.5, colour = "white") + 
                scale_color_manual (values = "black") + 
                scale_fill_manual (values = "grey") + 
                guides(color = FALSE), 
              include = "all", print = FALSE, scale = "relative")


#tiff(width = 15, height = 15, units = "in", res = 100, file = "output/odi_stability.tiff")
cowplot::plot_grid(s_fig[[1]] + 
                   theme(axis.text.x = element_blank(),
                         axis.title.x = element_blank()),
                   s_fig[[2]] + 
                   theme(axis.text.x = element_blank(),
                         axis.title.x = element_blank()),
                   s_fig[[3]] + 
                   theme(axis.text.x = element_blank(),
                         axis.title.x = element_blank()),
                   s_fig[[4]] + 
                   theme(axis.text.x = element_blank(),
                         axis.title.x = element_blank()),
                   s_fig[[5]] ,
                   labels = c("a. Cohort","b. Female", "c. Male", "d. Acute", "e. Chronic" ), 
                   vjust = 1, 
                   hjust = -2, 
                   ncol = 1,
                   nrow = 5)

dev.off()
```

##  CS coefficient

```{r, message=FALSE, warning=FALSE}
cs_coef <- tibble (data = c("Cohort","Female", "Male", "Acute", "Chronic" ),
                      stb = stb) %>%
  mutate (cor_stb = map (stb,
                         corStability)) %>%
  select (data, cor_stb) %>%
  unnest (cols = cor_stb) %>%
  ungroup() %>%
  mutate (measure = rep (c("betweenness", "closeness", "expectedInfluence", "strength"), 5)) %>%
  mutate (CS = round (cor_stb, 2)) %>%
  filter (measure %in% c("strength")) %>%
  dplyr::select (data, CS)

cs_coef %>%
  knitr::kable (caption = "Stability of centrality indices") %>%
  kable_styling()
```

